### ISSUE TITLE
Test the algorithm

### ISSUE THREAD

**Issue by lazarbeloica** [lazarbeloica/gi-Boyer-Moore#14]
Test the algorithm on the files given in the assignment definition.

**Comment by zafirovicmilan2** [comment]
update tests, instead of setUp use setUpClass(define class variables), and inside all methods, use class variables(static in C++) instead of object variables

integrationtests:
def setUp(self):                    =====>                      def setUpClass(cls):      
    self.skipTest("Not used for testing")  =====>      raise unittest.SkipTest("aaaaaaaaa")

**Comment by zafirovicmilan2** [comment]
https://stackoverflow.com/questions/23667610/what-is-the-difference-between-setup-and-setupclass-in-python-unittest
